# Generated by Django 4.1.7 on 2023-03-12 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelicula',
            name='genero',
            field=models.CharField(choices=[('Accion', 'Comedia'), ('Terror', 'Romantica'), ('Drama', 'Documental')], default=0, max_length=10),
            preserve_default=False,
        ),
    ]
