# Generated by Django 4.1.7 on 2023-03-30 19:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0004_comentario'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelicula',
            name='director',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pelicula',
            name='nacionalidad',
            field=models.CharField(default='none', max_length=100),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Serie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('genero', models.CharField(choices=[('Accion', 'Accion'), ('Terror', 'Terror'), ('Drama', 'Drama'), ('Documental', 'Documental'), ('Comedia', 'Comedia'), ('Romantica', 'Romantica')], max_length=10)),
                ('sinopsis', models.TextField()),
                ('temporadas', models.IntegerField()),
                ('duracion', models.IntegerField()),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
