# Generated by Django 4.1.7 on 2023-04-01 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_prueba_remove_pelicula_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Prueba',
        ),
    ]
