# Generated by Django 4.1.7 on 2023-04-01 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_delete_prueba'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelicula',
            name='image',
            field=models.ImageField(default='none', upload_to='files/movies'),
            preserve_default=False,
        ),
    ]
