# Generated by Django 4.1.7 on 2023-04-03 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_serie_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelicula',
            name='director',
            field=models.CharField(max_length=150),
        ),
    ]
