# Generated by Django 4.1.7 on 2023-04-03 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_alter_pelicula_director'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelicula',
            name='director',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='nacionalidad',
            field=models.CharField(max_length=200),
        ),
    ]
