# Generated by Django 4.1.7 on 2023-04-07 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_comentario_puntaje_alter_pelicula_genero_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='puntaje',
            field=models.CharField(choices=[('1', 1), ('2', 2), ('3', 3), ('4', 4), ('5', 5)], max_length=15),
        ),
    ]
