# Generated by Django 4.1.7 on 2023-04-18 00:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0023_comentariopelicula_comentarioserie_delete_comentario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelicula',
            name='image',
            field=models.ImageField(upload_to='base/Images/moviesPIC'),
        ),
        migrations.AlterField(
            model_name='serie',
            name='image',
            field=models.ImageField(upload_to='base/Images/seriesPIC'),
        ),
        migrations.CreateModel(
            name='Recomendacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('Pelicula', 'Pelicula'), ('Serie', 'Serie')], max_length=15)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
