# Generated by Django 4.1.7 on 2023-04-18 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0024_alter_pelicula_image_alter_serie_image_recomendacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='recomendacion',
            name='visto',
            field=models.BooleanField(default=True),
        ),
    ]
